### ISSUE TITLE
Problems with CO2 reading / unresponsiveness / different configuartion between sensor_s8.yaml & ag-pro.yaml(?)

### ISSUE THREAD

**Issue by moritz1000** [MallocArray/airgradient_esphome#35]
Hello,

I am having problems with the CO2 reading of my Airgradient Pro DIY (with an d1_mini).
I don't know what is causing this so I just throw out there what I do know:

![image](https://github.com/MallocArray/airgradient_esphome/assets/35174351/43d3b734-3151-44e9-aa66-ac702b294c42)

- Previously I used my own ESPHome configuartion. It had less functions but the CO2 reading was working reliably. 
- Recently I switched to your configuration (using https://github.com/MallocArray/airgradient_esphome/blob/main/airgradient-pro.yaml)
- The device becomes unresponsive every few days and does not send new data to Home Assistant / does not display updates on the OLED
- More often it's just the CO2 reading that it's broken: either it's stuck at some value, it displays "350" or is stuck at something ridiculously high like "655034"
- A reboot helps *sometimes*
- I am using a SGP40 instead of a SGP41 but 
> nox (Optional): NOx Index. Only available with SGP41. If a SGP40 sensor is detected this sensor will be ignored

this should not matter I guess since `sgp4x` does not measure the CO2 value - `senseair` does.
____

I assume you either install https://github.com/MallocArray/airgradient_esphome/blob/main/airgradient-pro.yaml where you are able to choose between different packages or install https://github.com/MallocArray/airgradient_esphome/blob/main/full_config/ag-pro.yaml ?

During my troubleshooting efforts, I observed that https://github.com/MallocArray/airgradient_esphome/blob/main/full_config/ag-pro.yaml sets `update_interval: 60s` (https://github.com/MallocArray/airgradient_esphome/blob/main/full_config/ag-pro.yaml#L261), while [sensor_s8.yaml ](https://github.com/MallocArray/airgradient_esphome/blob/main/packages/sensor_s8.yaml)does not specify this interval. Could you please clarify if this difference is intentional?
____

Despite these observations, I'm uncertain about the root cause of my issue. Given that my Airgradient DIY device is less than a year old, I suspect it's not a hardware problem.

Kind regards & thank you for your help.

**Comment by moritz1000** [comment]
Thank you for your help. 
Sadly the idea does not work: 
`Couldn't find ID 'nox'. Please check you have defined an ID with that name in your configuration.`
![image](https://github.com/MallocArray/airgradient_esphome/assets/35174351/b7908819-ee7e-44fb-9a44-24e138072d64)

Since my Airgradient/CO2 reading is unusable in the last few days I will create a minimal configuartion which just sends the CO2 value and nothing more in order to rule out a hardware defect. I'll report back!

**Comment by MallocArray** [comment]
Shoot, didn't think that all the way through.  Since the API upload and Display modules all reference the nox sensor ID, just removing it would cause both of them to have an error.

**Comment by moritz1000** [comment]
I think I fixed my issue.
When looking at the logs I saw things like:
```
[08:04:40][D][senseair:059]: SenseAir Received CO₂=216ppm Status=0x00
[08:04:40][D][sensor:093]: 'CO2': Sending state 350.00000 ppm with 0 decimals of accuracy
```
which explained the value being stuck at 350 so often! For whatever reason the SenseAir was measuring impossible low values and then sending the `min_value: 350` to Home Assistant.
Also errors like
```
[16:52:40][W][senseair:030]: Invalid preamble from SenseAir! ac4737fe 04080000 00000001 00
# and
[12:33:40] [E] [uart:015]: Reading from UART timed out at byte 9!
[12:33:40] [W] [senseair:024]: Reading data from SenseAir failed!
```

___

I completely re-flashed my the ESPHome with `airgradient_esphome` and the error side of things was already looking much better but the CO2 values were still "impossible" wrong. So I ran a `SenseAir S8 Calibration` near an open window and now everything seems back to normal :).

I'll disable `SenseAir S8 Automatic Background Calibration` for now and observe for now.
___

Again thank you for your help! I guess sometimes it takes more than a reboot - a re-flash to fix things :).

**Comment by MallocArray** [comment]
Glad you got it going.  A reading fixed at 350 does currently mean that the readings are showing possible invalid values, since I would be surprised if there was a situation that you would hit actual 350 ppm environment, but I might end up removing that, and if you get lower than 400, it will be what it is.

I have had to reinstall a few times.  I do also see the "Invalid preamble" message sometimes even when things looks to be running as expected, but it doesn't result in a value of 65k for me.

Glad it is going

**Comment by moritz1000** [comment]
Hey :),
So small update here: The problems came back. I think it has to do with the automatic background calibration!

```
[21:49:06][D][senseair:059]: SenseAir Received CO₂=57ppm Status=0x00
[21:49:06][D][sensor:093]: 'CO2': Sending state 350.00000 ppm with 0 decimals of accuracy
```

The CO2 sensor is measuring absolute garbage e.g.: **57ppm**.

I am pretty sure that my problems started happening again after about 180 hours = 7,5 days, so exactly when the [automatic background calibration](https://esphome.io/components/sensor/senseair.html#senseair-abc-enable-action) happens.

___
I'll re-flash the firmware soon, disable abc and see what happens.

**Comment by MallocArray** [comment]
You probably don't even need to reflash the firmware.  You should already have a button to trigger a manual calibration, so if you take it outside for 5 minutes (or near an open window), then do the manual calibration, and wait another 5-10 minutes and bring inside, hopefully that takes care of it.

There is another issue open for very similar, I'm going to update there as well.

**Comment by moritz1000** [comment]
> hopefully that takes care of it.

Thank you! 
This time a simple manual calibration seems to have worked, last time I did have to re-flash.

What I don't understand is why I keep having problems with the abc.
The implementen in your repository is not different from what is described here, I think: https://esphome.io/components/sensor/senseair.html#senseair-co-2-sensor
___

Anyways I turned off abc for good and hope that I won't see the problem again in 8 days.

Again, many thanks!
